services:
  ollama-cloud-proxy:
    build: .
    container_name: "ollama-cloud-proxy"
    ports:
      - "11434:11434"
    environment:
      - ALLOW_UNAUTHENTICATED_ACCESS=${ALLOW_UNAUTHENTICATED_ACCESS:-true}
      - APP_VERSION=${APP_VERSION:-v1.20.11-local}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: always
